### PR TITLE
added xcb-util-cursor to dependencies

### PR DESCRIPTION
**Pull request by lordadamson**
I don't have a desktop installed (I'm compiling one from scratch) so that's why I had to install this package.

### CODE REVIEW

**Comment by plfiorini** [comment]
xcb-util-cursor is required only for the xwayland plugin (whose build is enabled by default).

Could you please rephrase it so that shows that, like:

If you enable XWayland support you also need:

- link to xcb-util-cursor

**Comment by lordadamson** [comment]
Alright sir! done.

**Comment by plfiorini** [comment]
Manually removed the first commit and merged.
Thanks.

**Comment by lordadamson** [comment]
Thank you sir.

**Pull request closed without merging**
