### PR TITLE
Initial work on shared window manager code

### PR DESCRIPTION
**Pull request by iBeliever**
This is an initial pass at implementing #77. As you mentioned in the ticket, this will probably be affected by the compositor context property.

However, I had already started on this for use in Papyros and thought it might be worth getting into Green Island until you have a complete solution for #70. It's already a big improvement over all the duplicate window code in different compositors.

### CODE REVIEW

**Comment by iBeliever** [comment]
@plfiorini Could you please look over this pull request and see if it's something you can include?

**Comment by iBeliever** [comment]
@plfiorini It's much easier if you review pull requests by commenting on the full diff. A lot of stuff changes between each commit, so basically unless you comment on the full diff, you commenting on old code. 

Anyhow, if you're happy with the work I have so far, I can squash it all down into one nice commit for merging. Also, the licenses for components copied from the sample compositor need to be updated to the standard compositor library license - are you okay with relicensing those files?

**Comment by iBeliever** [comment]
@plfiorini Unfortunately I rebased my branch on top of master and pushed, so all our commits got deleted - sorry.

**Comment by plfiorini** [comment]
@iBeliever Don't worry I still have them in the inbox.

**Comment by plfiorini** [comment]
Library license on master should be fine now.

**Comment by iBeliever** [comment]
@plfiorini I've squashed all the work into one commit and updated the license of all the components to be LGPLv2.1+. Could you please review again and let me know what else needs to get done before this gets merged?

**Comment by iBeliever** [comment]
@plfiorini I agree that the window and workspace models should be in C++ (though workspaces need to be managed on a per-screen basis). However, since your original code didn't handle workspaces on a global level, and this is already an improvement over the previous code, would you be willing to merge this in as-is?

I haven't begun to work on multiple-screen support for Papyros yet, so I'm not ready to invest the time in moving the workspace and window models into C++.

**Comment by iBeliever** [comment]
@plfiorini Any update on when you'll be able to review and merge this in? I'd really like to get it merged into upstream before releasing v0.1 of Papyros Shell next month.

**Comment by plfiorini** [comment]
Move to 0.7.0 because 0.6.0 really need to be stabilized first.

**Comment by plfiorini** [comment]
There's a window manager component now with the new API.

**Pull request closed without merging**
